# Generated by Django 5.0 on 2023-12-31 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='comment',
        ),
    ]
